version: '3.8'

services:
  db:
    container_name: db-cars
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker_cars
      MYSQL_USER: lenochka
      MYSQL_PASSWORD: popstvuet
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql